apiVersion: apps/v1 
kind: Deployment
metadata:
  name: www-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: www-lbl
  template:
    metadata:
      labels:
        app: www-lbl
    spec:
      containers:
      - name: www-pod
        image: heh8mons7000/app_web:1.0
        ports:
          - containerPort: 5000
             

             